import contextlib
import hashlib
import importlib
import io
import json
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
import zipfile
from pathlib import Path
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from artifacts import AGENTS_BLOCK_BUDGET, CORE, GEMINI_BLOCK_BUDGET, WEB_SKILL, persistent_core, render_agents_block, render_claude, render_web, split_gemini_instructions

import importlib.util
spec = importlib.util.spec_from_file_location("web_generator", ROOT / "scripts/generate-web-artifacts.py")
web_generator = importlib.util.module_from_spec(spec)
spec.loader.exec_module(web_generator)

style_spec = importlib.util.spec_from_file_location("style_generator", ROOT / "scripts/generate-output-style.py")
style_generator = importlib.util.module_from_spec(style_spec)
style_spec.loader.exec_module(style_generator)

agents_spec = importlib.util.spec_from_file_location("agents_generator", ROOT / "scripts/generate-agents-block.py")
agents_generator = importlib.util.module_from_spec(agents_spec)
agents_spec.loader.exec_module(agents_generator)


REFERENCES_URL = "https://github.com/monkey1wizard/clear-writing-kit/blob/main/docs/references.md"
CITATION_KEY = re.compile(r"`\[([A-Za-z][A-Za-z0-9]*)\]`")
BARE_CITATION_KEY = re.compile(r"\[[A-Za-z][A-Za-z0-9]*\](?!\()")
RELATIVE_DOCS_LINK = re.compile(r"\]\((?![a-z][a-z0-9+.-]*:)[^)]*docs/")
CERTIFICATION_CLAIM = re.compile(r"(?i)\b(?:compl(?:y|ies|iant|iance)|certif\w*|conform\w*)\b|符合|認證|準拠|認証")
STAMP_LINE = re.compile(r"^<!-- (?:Generated by scripts/generate-web-artifacts\.py\. )?Source SHA-256: [0-9a-f]{64} -->\n", re.M)

# Heading of the closing citation section and the phrase that introduces project-authored rules, per maintained rule file.
SOURCES_SECTIONS = {
    "accuracy": ("Sources", "Project-authored rules"),
    "en-US": ("Sources", "Project-authored rules"),
    "local-checks": ("Sources", "Project-authored rules"),
    "zh-TW": ("資料來源", "本專案自訂的規則"),
    "zhtw-checks": ("資料來源", "本專案自訂的規則"),
    "ja-JP": ("出典", "独自に定めた"),
}
# Citations each rule file must keep. Files may cite further keys that the reference list defines.
REQUIRED_CITATIONS = {
    "accuracy": {"ISO2023", "SpeakHumanTW2026", "Yomiyasu2026"},
    "en-US": {"ASDSTE1002025"},
    "zh-TW": {"SpeakHumanTW2026"},
    "ja-JP": {"Bunka2022", "Yomiyasu2026"},
    "local-checks": {"Textlint1580", "TextlintRulePresetJaTechnicalWriting1202", "TextlintRuleWriteGood200", "TextlintRuleNoZeroWidthSpaces101"},
    "zhtw-checks": {"ZhtwMCP"},
}
# SHA-256 of each rule file's text above its citation section, with LF line endings and trailing newlines removed.
# A change that intentionally edits rule text must update the matching digest.
RULE_PREFIX_SHA256 = {
    "accuracy": "bb975b90381d3bc965a17cf117df98ce70191a9134242011cfe348f57e75677f",
    "en-US": "aef28977a419d41c60600f9e79d4cd34d78a242b923e505dfb8d1bb2f360cc50",
    "ja-JP": "206ae66f7fa01577ba806ce74ba0d38f01f96834ddc119bf50aba72c0c5528b2",
    "zh-TW": "3c456744656c6a8b7b9529ada08a55d2fc7c7d28544584b8d69e39dc106b1ab8",
    "local-checks": "812eb093d005e9990af013a541f36f6062da242b0c9743c2f1f749b4812258cb",
    "zhtw-checks": "f6735588d51c744622c508d4e5b2cf9b333660aecd181da44a2e0fbbcf63a3ff",
}
# SHA-256 of generator output for the instruction files with the source stamp line removed.
# A change that intentionally edits the persistent instruction excerpt or its templates must update the matching digest.
# SHA-256 of the persistent instruction excerpt that every account-level and agent instruction file embeds.
PERSISTENT_CORE_SHA256 = "d8d0e1fb7c15b22b44c7e9e0f2e6e9b4004be7ce9cd07b2c609e46990583361d"
# Exact repository snapshot that informed the Japanese style-signal rules and the shared meaning check.
YOMIYASU_COMMIT = "c2ffae670994fec96daef92e0bc219f5c1923113"
# Heading and ordered category names of the Japanese style-signal section.
JA_STYLE_SIGNAL_HEADING = "定型的な言い回し"
JA_STYLE_SIGNAL_CATEGORIES = ("比喩動詞", "英語の直訳構文", "空疎な評価語", "前置きと文末の付け足し", "定型の結び")
INSTRUCTION_BODY_SHA256 = {
    "web-instructions/chatgpt.md": "56c9e4242b176484e82342bcdf83cbffc5ced60d2fb57c094de10d053fb605d3",
    "web-instructions/gemini.md": "fd174653e95216f66146c4c968a3c3ee82a4af4f20393bb6775cf0cb3c327519",
    "install/agents-block.md": "a65abcc9b87088423dd65fb0cbeecb8a5277429e887a598f2151ead8c1e3007e",
}


def read_lf(path: Path) -> str:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n")


def split_sources_section(name: str) -> tuple[str, str]:
    """Return the rule text above the closing citation section and the section itself."""
    text = read_lf(ROOT / CORE / "references" / (name + ".md"))
    heading = "\n## " + SOURCES_SECTIONS[name][0] + "\n"
    if text.count(heading) != 1:
        raise AssertionError(f"{name}.md must contain exactly one citation section heading")
    prefix, section = text.split(heading)
    if "\n## " in section:
        raise AssertionError(f"{name}.md citation section must be the last section")
    return prefix, heading.lstrip("\n") + section


def reference_entries() -> dict[str, tuple[str, str]]:
    """Map each citation key in docs/references.md to its group heading and entry text."""
    entries, group = {}, None
    for line in read_lf(ROOT / "docs/references.md").splitlines():
        if line.startswith("## "):
            group = line[3:]
            continue
        match = re.match(r"^- `\[([A-Za-z][A-Za-z0-9]*)\]` (.+)$", line)
        if match:
            if match.group(1) in entries:
                raise AssertionError("Duplicate citation key: " + match.group(1))
            entries[match.group(1)] = (group, match.group(2))
    return entries


class Artifacts(unittest.TestCase):
    def test_reference_citation_contract(self):
        reference_text = read_lf(ROOT / "docs/references.md")
        groups = re.findall(r"^## (.+)$", reference_text, re.M)
        self.assertEqual(groups, ["Standards and guidelines", "Software"])
        self.assertNotRegex(reference_text, r"(?i)used by")
        self.assertNotRegex(reference_text, CERTIFICATION_CLAIM)
        entries = reference_entries()
        self.assertTrue(entries)

        package = json.loads((ROOT / "writing/package.json").read_text(encoding="utf-8"))
        pinned = {**package.get("dependencies", {}), **package.get("devDependencies", {})}
        for group in groups:
            order = []
            for key, (entry_group, entry) in entries.items():
                if entry_group != group:
                    continue
                match = re.match(r"^(.+?)\. \((\d{4}|n\.d\.)\)\. \*\[[^\]]+\]\(https://[^)]+\)\*", entry)
                self.assertIsNotNone(match, key)
                order.append((match.group(1).casefold(), match.group(2)))
                if group == "Software":
                    npm = re.search(r"https://www\.npmjs\.com/package/([^/)]+)/v/([^)]+)\)", entry)
                    if npm:
                        name, version = npm.groups()
                        self.assertEqual(pinned.get(name), version, key)
                        self.assertIn(f"(Version {version})", entry)
                        self.assertTrue(key.endswith(version.replace(".", "")), key)
                    else:
                        # Host-provided software has no repository pin. Cite it without a version claim.
                        self.assertNotIn("Version", entry, key)
                        self.assertRegex(entry, r"Retrieved [A-Z][a-z]+ \d{1,2}, \d{4}, from <https://", key)
            self.assertEqual(order, sorted(order), group)
        for key in ("ISO2023", "ASDSTE1002025", "SpeakHumanTW2026", "Bunka2022", "Yomiyasu2026"):
            self.assertEqual(entries[key][0], "Standards and guidelines", key)
        for key in ("Textlint1580", "TextlintRulePresetJaTechnicalWriting1202", "TextlintRuleWriteGood200", "TextlintRuleNoZeroWidthSpaces101", "ZhtwMCP"):
            self.assertEqual(entries[key][0], "Software", key)
        self.assertIn("e180f0a", entries["SpeakHumanTW2026"][1])
        self.assertIn("/tree/" + YOMIYASU_COMMIT + ")", entries["Yomiyasu2026"][1])
        self.assertIn("(Commit " + YOMIYASU_COMMIT[:7] + ")", entries["Yomiyasu2026"][1])
        self.assertNotRegex(entries["Yomiyasu2026"][1], r"(?i)v?1\.1\.0|release")

        self.assertNotRegex(persistent_core(ROOT), BARE_CITATION_KEY)
        maintained = {p.stem for p in (ROOT / CORE / "references").glob("*.md")}
        self.assertEqual(maintained, set(SOURCES_SECTIONS))
        cited = set()
        for name in sorted(maintained):
            with self.subTest(rule_file=name):
                prefix, section = split_sources_section(name)
                self.assertEqual(hashlib.sha256(prefix.rstrip("\n").encode("utf-8")).hexdigest(), RULE_PREFIX_SHA256[name])
                self.assertNotRegex(prefix, CITATION_KEY)
                self.assertIn("](" + REFERENCES_URL + ")", section)
                self.assertNotRegex(prefix + section, RELATIVE_DOCS_LINK)
                self.assertNotRegex(section, CERTIFICATION_CLAIM)
                self.assertIn(SOURCES_SECTIONS[name][1], section)
                keys = set(CITATION_KEY.findall(section))
                self.assertLessEqual(REQUIRED_CITATIONS[name], keys)
                cited |= keys
                for line in section.splitlines():
                    if "`[SpeakHumanTW2026]`" in line:
                        self.assertIn("e180f0a", line)
                        self.assertTrue("informed by" in line or "受其啟發" in line, line)
                        self.assertNotRegex(line, r"(?i)deriv|follow|推導|依據")
                    if "`[Yomiyasu2026]`" in line:
                        self.assertIn(YOMIYASU_COMMIT[:7], line)
                        self.assertNotRegex(line, r"(?i)v?1\.1\.0|release")
                        self.assertTrue("informed by" in line or "着想を得た" in line, line)
                        self.assertNotRegex(line, r"(?i)deriv|follow|基づく|準拠")
        self.assertEqual(cited - set(entries), set(), "cited keys missing from docs/references.md")
        self.assertEqual(set(entries) - cited, set(), "reference entries without a rule-file citation")

    def test_reference_citation_projections(self):
        outputs = render_web()
        self.assertEqual(len(outputs), 7)
        for relative, text in outputs.items():
            with self.subTest(output=relative.as_posix()):
                self.assertEqual(read_lf(ROOT / relative), text)
                self.assertNotRegex(text, RELATIVE_DOCS_LINK)
                if relative.parent == WEB_SKILL / "references":
                    self.assertIn("](" + REFERENCES_URL + ")", text)
        agents_block = read_lf(ROOT / "install/agents-block.md")
        self.assertEqual(agents_block, render_agents_block())
        for relative, expected in INSTRUCTION_BODY_SHA256.items():
            with self.subTest(instructions=relative):
                body = STAMP_LINE.sub("", read_lf(ROOT / relative))
                self.assertNotRegex(body, CITATION_KEY)
                self.assertEqual(hashlib.sha256(body.encode("utf-8")).hexdigest(), expected)
        for relative in ("knowledge/rules/accuracy.md", "knowledge/rules/en-US.md", "knowledge/rules/ja-JP.md", "knowledge/rules/zh-TW.md", "knowledge/checks/local-checks.md", "knowledge/checks/zhtw-checks.md"):
            with self.subTest(concept=relative):
                text = read_lf(ROOT / relative)
                self.assertIn("](" + REFERENCES_URL + ")", text)
                self.assertNotRegex(text, RELATIVE_DOCS_LINK)
        style = read_lf(ROOT / "output-styles/clear-writing-kit.md")
        self.assertEqual(style, render_claude())
        self.assertEqual(style.count("](" + REFERENCES_URL + ")"), len(SOURCES_SECTIONS))
        self.assertNotRegex(style, RELATIVE_DOCS_LINK)

    def test_ja_ai_tone_guidance_contract(self):
        text = read_lf(ROOT / CORE / "references/ja-JP.md")
        heading = "\n## " + JA_STYLE_SIGNAL_HEADING + "\n"
        self.assertEqual(text.count(heading), 1)
        section = text.split(heading, 1)[1].split("\n## ", 1)[0]
        bullets = [line for line in section.splitlines() if line.startswith("- ")]
        self.assertEqual([line[2:].split("：", 1)[0] for line in bullets], list(JA_STYLE_SIGNAL_CATEGORIES))
        for line in bullets:
            with self.subTest(category=line[2:].split("：", 1)[0]):
                rule, examples = line.split("：", 1)[1].split("例：", 1)
                self.assertEqual(rule.count("。"), 1)
                self.assertTrue(rule.strip().endswith("。"))
                self.assertIn(len(re.findall(r"「[^」]+」", examples)), (1, 2))
                self.assertEqual(re.sub(r"「[^」]+」", "", examples).strip(), "")
        prose = "\n".join(line for line in section.splitlines() if not line.startswith("- "))
        # Scope, meaning limit, protected wording, uncertainty fallback, and no authorship inference.
        for phrase in (
            "文書と会話の両方に適用する",
            "意味と範囲が変わらない場合に限る",
            "定義済みの用語、標準的な技術用語、製品名、引用",
            "元の表現を残す",
            "書き手が人か機械かを判断する証拠にはしない",
            "流行語の一覧や、語ごとの置換表は使わない",
        ):
            self.assertIn(phrase, prose)
        # Time-bound vocabulary lists and per-word replacement tables stay out of the rule.
        self.assertNotIn("|", section)
        self.assertNotIn("→", section)
        self.assertNotRegex(section, r"20\d\d年")

        accuracy = read_lf(ROOT / CORE / "references/accuracy.md")
        meaning = accuracy.split("\n## Meaning check\n", 1)[1].split("\n## ", 1)[0]
        for phrase in (
            "facts, numbers, units, deadlines, negation, conditions, exceptions, scope, attribution, and certainty",
            "relative weight of each point",
            "function of each sentence",
            "evaluation, explanation, request, or plan",
        ):
            self.assertIn(phrase, meaning)
        self.assertNotIn("relative weight", persistent_core(ROOT))
        self.assertNotIn("function of each sentence", persistent_core(ROOT))
        self.assertNotIn("relative weight", text)

    def test_ja_ai_tone_projection_contract(self):
        self.assertEqual(hashlib.sha256(persistent_core(ROOT).encode("utf-8")).hexdigest(), PERSISTENT_CORE_SHA256)
        outputs = {relative.as_posix(): text for relative, text in render_web().items()}
        for name in ("accuracy", "ja-JP"):
            projected = WEB_SKILL / "references" / (name + ".md")
            with self.subTest(projection=projected.as_posix()):
                self.assertEqual(read_lf(ROOT / projected), outputs[projected.as_posix()])
                self.assertEqual(read_lf(ROOT / projected), read_lf(ROOT / CORE / "references" / (name + ".md")))
        markers = {"accuracy": "relative weight of each point", "ja-JP": "## " + JA_STYLE_SIGNAL_HEADING}
        style = read_lf(ROOT / "output-styles/clear-writing-kit.md")
        for name, marker in markers.items():
            concept = read_lf(ROOT / "knowledge/rules" / (name + ".md"))
            with self.subTest(marker=marker):
                self.assertIn(marker, concept)
                self.assertIn("Yomiyasu2026", concept)
                self.assertIn(marker, style)
        for relative in ("web-instructions/chatgpt.md", "web-instructions/gemini.md"):
            with self.subTest(instructions=relative):
                body = STAMP_LINE.sub("", read_lf(ROOT / relative))
                self.assertEqual(hashlib.sha256(body.encode("utf-8")).hexdigest(), INSTRUCTION_BODY_SHA256[relative])
                self.assertNotIn("relative weight", body)
                self.assertNotIn(JA_STYLE_SIGNAL_HEADING, body)
        agents_block = read_lf(ROOT / "install/agents-block.md").encode("utf-8")
        self.assertEqual(hashlib.sha256(agents_block).hexdigest(), INSTRUCTION_BODY_SHA256["install/agents-block.md"])
        self.assertEqual(read_lf(ROOT / "install/agents-block.md"), render_agents_block())

    def test_agents_block_has_required_content_and_byte_limit(self):
        block = render_agents_block()
        skill = (ROOT / CORE / "SKILL.md").read_text(encoding="utf-8")
        version = re.search(r"^  version:\s*([^\s]+)\s*$", skill, re.M).group(1)
        self.assertTrue(block.startswith(f"<!-- clear-writing-kit:begin v={version} -->\n"))
        self.assertTrue(block.endswith("<!-- clear-writing-kit:end -->\n"))
        self.assertLess(len(block.encode("utf-8")), AGENTS_BLOCK_BUDGET)
        for expected in (
            "2.0.0", "coding-agent-writing", "lintText",
            "`node`", "`deno run -A`", "`bun`",
            "`<runtime command> <home>/.clear-writing-kit/cwk.mjs check`",
            "Resolve `<home>`", persistent_core(ROOT),
        ):
            self.assertIn(expected, block)
        self.assertNotRegex(block, r"[A-Za-z]:[/\\]")
        self.assertNotIn("/Users/", block)
        self.assertNotIn("/home/", block.replace("<home>", ""))

    def test_agents_block_rejects_size_at_or_above_limit(self):
        with tempfile.TemporaryDirectory() as d:
            root = Path(d)
            source = root / CORE / "references/accuracy.md"
            source.parent.mkdir(parents=True)
            source.write_text("<!-- instructions:begin -->\n" + "x" * AGENTS_BLOCK_BUDGET + "\n<!-- instructions:end -->", encoding="utf-8")
            skill = root / CORE / "SKILL.md"
            skill.parent.mkdir(parents=True, exist_ok=True)
            skill.write_text("---\nmetadata:\n  version: 1.2.3\n---\n", encoding="utf-8")
            with self.assertRaisesRegex(ValueError, "smaller than 2048 bytes"):
                render_agents_block(root)

    def test_agents_block_cli_check_and_version_drift(self):
        with tempfile.TemporaryDirectory() as d:
            target = Path(d) / "agents-block.md"
            cmd = [sys.executable, str(ROOT / "scripts/generate-agents-block.py"), "--output", str(target)]
            self.assertNotEqual(subprocess.run(cmd + ["--check"], capture_output=True).returncode, 0)
            subprocess.run(cmd, check=True, capture_output=True)
            subprocess.run(cmd + ["--check"], check=True, capture_output=True)
            target.write_text("stale", encoding="utf-8")
            self.assertNotEqual(subprocess.run(cmd + ["--check"], capture_output=True).returncode, 0)

        with tempfile.TemporaryDirectory() as d:
            root = Path(d)
            shutil.copytree(ROOT / CORE, root / CORE)
            shutil.copytree(ROOT / "scripts", root / "scripts")
            skill_file = root / CORE / "SKILL.md"
            content = skill_file.read_text(encoding="utf-8")
            skill_file.write_text(content.replace("version: 2.0.0", "version: 2.0.1"), encoding="utf-8")
            drifted_block = render_agents_block(root)
            self.assertTrue(drifted_block.startswith("<!-- clear-writing-kit:begin v=2.0.1 -->\n"))
            self.assertNotEqual(drifted_block, (ROOT / "install/agents-block.md").read_text(encoding="utf-8"))

    def test_committed_agents_block_matches_generated_content(self):
        self.assertEqual((ROOT / "install/agents-block.md").read_text(encoding="utf-8"), render_agents_block())

    def test_repository_branding_preserves_distinct_skill_names(self):
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        self.assertTrue(readme.startswith("# clear-writing-kit\n\nWriting rules, skills, and checks for en-US, zh-TW, and ja-JP.\n"))
        package = json.loads((ROOT / "writing/package.json").read_text(encoding="utf-8"))
        lock = json.loads((ROOT / "writing/package-lock.json").read_text(encoding="utf-8"))
        self.assertEqual(package["name"], "clear-writing-kit-checks")
        self.assertEqual(lock["name"], package["name"])
        self.assertEqual(lock["packages"][""]["name"], package["name"])
        core = (ROOT / CORE / "SKILL.md").read_text(encoding="utf-8")
        outputs = render_web()
        self.assertIn("\nname: coding-agent-writing\n", core)
        self.assertIn("\nname: web-answer-writing\n", outputs[WEB_SKILL / "SKILL.md"])
        for text in (core, outputs[WEB_SKILL / "SKILL.md"]):
            self.assertIn("toolkit: clear-writing-kit", text)
        for text in (*outputs.values(), render_claude()):
            self.assertNotIn("accurate-answer", text)

    def test_default_style_name_changes_without_deleting_existing_style(self):
        self.assertEqual(style_generator.DEFAULT_OUTPUT, ROOT / "output-styles" / "clear-writing-kit.md")
        self.assertEqual(style_generator.DEFAULT_OUTPUT.name, "clear-writing-kit.md")
        self.assertEqual(style_generator.DEFAULT_OUTPUT.parent.name, "output-styles")
        with tempfile.TemporaryDirectory() as d, contextlib.redirect_stdout(io.StringIO()):
            root = Path(d)
            old = root / "accurate-answer.md"
            old.write_text("existing user style", encoding="utf-8")
            target = root / style_generator.DEFAULT_OUTPUT.name
            with patch.object(style_generator, "DEFAULT_OUTPUT", target):
                with patch.object(sys, "argv", ["generate-output-style.py"]):
                    self.assertEqual(style_generator.main(), 0)
                with patch.object(sys, "argv", ["generate-output-style.py", "--check"]):
                    self.assertEqual(style_generator.main(), 0)
            self.assertIn("\nname: clear-writing-kit\n", target.read_text(encoding="utf-8"))
            self.assertEqual(old.read_text(encoding="utf-8"), "existing user style")

    def test_committed_style_matches_generated_content(self):
        committed_style = ROOT / "output-styles" / "clear-writing-kit.md"
        self.assertEqual(committed_style.read_text(encoding="utf-8"), render_claude())

    def test_default_web_preview_uses_new_name(self):
        with tempfile.TemporaryDirectory() as d, contextlib.redirect_stdout(io.StringIO()):
            with patch.object(web_generator.tempfile, "mkdtemp", return_value=d) as make_temp:
                with patch.object(sys, "argv", ["generate-web-artifacts.py"]):
                    self.assertEqual(web_generator.main(), 0)
                make_temp.assert_called_once_with(prefix="clear-writing-kit-web-")
            self.assertTrue(web_generator.check(Path(d), render_web()))

    def test_web_scope_and_self_contained_links(self):
        outputs = render_web()
        self.assertEqual(len(outputs), 7)
        self.assertTrue(all(str(p).startswith(("web-skills", "web-instructions")) for p in outputs))
        for relative, text in outputs.items():
            for target in re.findall(r"\]\(([^)]+)\)", text):
                if not target.startswith(("https:", "#")):
                    resolved = Path(relative.parent, target)
                    self.assertIn(resolved, outputs)
        self.assertFalse(any("local-checks" in str(p) or "zhtw-checks" in str(p) for p in outputs))

    def test_shared_source_change_propagates(self):
        with tempfile.TemporaryDirectory() as d:
            root = Path(d)
            shutil.copytree(ROOT / CORE, root / CORE)
            shutil.copytree(ROOT / "scripts/templates", root / "scripts/templates")
            before = render_web(root)
            source = root / CORE / "references/accuracy.md"
            source.write_text(source.read_text(encoding="utf-8").replace("Lead with the answer.", "Lead with the verified answer."), encoding="utf-8")
            after = render_web(root)
            for name in ("chatgpt", "gemini"):
                self.assertIn("Lead with the verified answer.", after[Path("web-instructions") / (name + ".md")])
            self.assertNotEqual(before[WEB_SKILL / "references/accuracy.md"], after[WEB_SKILL / "references/accuracy.md"])
            self.assertIn("Lead with the verified answer.", render_claude(root))

    def test_check_detects_missing_stale_and_extra_files(self):
        outputs = render_web()
        with tempfile.TemporaryDirectory() as d, contextlib.redirect_stderr(io.StringIO()):
            root = Path(d)
            self.assertFalse(web_generator.check(root, outputs))
            for p, text in outputs.items():
                (root / p).parent.mkdir(parents=True, exist_ok=True)
                (root / p).write_text(text, encoding="utf-8")
            self.assertTrue(web_generator.check(root, outputs))
            (root / WEB_SKILL / "SKILL.md").write_text("stale", encoding="utf-8")
            self.assertFalse(web_generator.check(root, outputs))
            (root / WEB_SKILL / "SKILL.md").write_text(outputs[WEB_SKILL / "SKILL.md"], encoding="utf-8")
            (root / WEB_SKILL / "extra.md").write_text("extra", encoding="utf-8")
            self.assertFalse(web_generator.check(root, outputs))

    def test_archive_members_and_deterministic_content(self):
        with tempfile.TemporaryDirectory() as d:
            root = Path(d)
            args = [sys.executable, str(ROOT / "scripts/generate-web-artifacts.py"), "--output-dir", str(root / "out"), "--archive-dir", str(root / "zip")]
            subprocess.run(args, check=True, capture_output=True)
            with zipfile.ZipFile(root / "zip/web-answer-writing.zip") as archive:
                expected = {p.relative_to(WEB_SKILL).as_posix(): t for p, t in render_web().items() if p.is_relative_to(WEB_SKILL)}
                self.assertEqual(set(archive.namelist()), set(expected))
                for p, t in expected.items():
                    self.assertEqual(archive.read(p).decode("utf-8"), t)
            self.assertEqual(render_web(), render_web())

    def test_claude_embeds_local_procedures_without_file_links(self):
        text = render_claude()
        self.assertIn("工具可用時，必須在交付前執行檢查", text)
        self.assertIn("## Embedded ja-JP", text)
        self.assertNotRegex(text, r"\]\((?!https:)(?:references/)?[^)]+\.md\)")
        with tempfile.TemporaryDirectory() as d:
            target = Path(d) / "style.md"
            cmd = [sys.executable, str(ROOT / "scripts/generate-output-style.py"), "--output", str(target)]
            self.assertNotEqual(subprocess.run(cmd + ["--check"], capture_output=True).returncode, 0)
            subprocess.run(cmd, check=True, capture_output=True)
            subprocess.run(cmd + ["--check"], check=True, capture_output=True)
            target.write_text("stale", encoding="utf-8")
            self.assertNotEqual(subprocess.run(cmd + ["--check"], capture_output=True).returncode, 0)

    def test_user_gemini_requirements_and_compact_limit(self):
        outputs = render_web()
        text = outputs[Path("web-instructions/gemini.md")]
        self.assertIn("Must check the date of today then search for the latest data to answer me.", text)
        self.assertIn("Do not proactively ask follow-up questions.", text)
        self.assertIn("Always reply in Traditional Chinese when I ask in Chinese.", text)
        self.assertIn("Never use `;` or `；`", text)
        blocks = re.findall(r"```text\n(.*?)\n```", text, re.S)
        self.assertGreater(len(blocks), 1)
        self.assertTrue(all(len(block) <= GEMINI_BLOCK_BUDGET for block in blocks))
        original = (ROOT / "scripts/templates/gemini.txt").read_text(encoding="utf-8").replace("{{core}}", persistent_core(ROOT)).strip()
        self.assertEqual(" ".join(" ".join(blocks).split()), " ".join(original.split()))
        block = outputs[Path("web-instructions/chatgpt.md")].split("```text\n")[1].split("\n```")[0]
        self.assertLessEqual(len(block), 1500)
        for platform in ("chatgpt", "gemini"):
            instructions = outputs[Path("web-instructions") / (platform + ".md")]
            self.assertIn("Use en-US spelling.", instructions)
            self.assertIn("For ja-JP documents, use である forms, not だ forms", instructions)
            self.assertIn("Apply document style to documents drafted in chat.", instructions)
            self.assertIn("For ja-JP conversations, use polite text and lists.", instructions)

    def test_gemini_split_rejects_oversized_sentence(self):
        with self.assertRaisesRegex(ValueError, "exceeds packaging budget"):
            split_gemini_instructions("A" * (GEMINI_BLOCK_BUDGET + 1))

    def test_readme_languages_have_equal_commands_and_local_links(self):
        text = (ROOT / "README.md").read_text(encoding="utf-8")
        sections = re.split(r"^## (?:English|繁體中文|日本語)\n", text, flags=re.M)[1:]
        self.assertEqual(len(sections), 3)
        commands = [re.findall(r"```powershell\n(.*?)```", section, re.S) for section in sections]
        self.assertEqual(commands[0], commands[1])
        self.assertEqual(commands[0], commands[2])
        links = [{p for p in re.findall(r"\]\(([^)]+)\)", section) if not p.startswith(("https:", "#"))} for section in sections]
        self.assertEqual(links[0], links[1])
        self.assertEqual(links[0], links[2])
        for target in links[0]:
            self.assertTrue((ROOT / target).is_file(), target)


if __name__ == "__main__":
    unittest.main()
