"""Render self-contained platform artifacts from shared source files."""
from __future__ import annotations

import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROJECT_NAME = "clear-writing-kit"
PROJECT_TITLE = "Clear Writing Kit"
CORE = Path("skills/coding-agent-writing")
TEMPLATES = Path("scripts/templates")
SHARED = ("accuracy", "en-US", "zh-TW", "ja-JP")
LOCAL = ("local-checks", "zhtw-checks")
WEB_SKILL = Path("web-skills/web-answer-writing")
GEMINI_BLOCK_BUDGET = 900


def read(root: Path, path: Path) -> str:
    return (root / path).read_text(encoding="utf-8")


def digest(root: Path, paths: list[Path]) -> str:
    value = hashlib.sha256()
    for path in sorted(paths):
        value.update(path.as_posix().encode("utf-8") + b"\0")
        value.update(read(root, path).replace("\r\n", "\n").encode("utf-8") + b"\0")
    return value.hexdigest()


def shared_paths() -> list[Path]:
    return [CORE / "references" / (name + ".md") for name in SHARED]


def persistent_core(root: Path) -> str:
    source = read(root, CORE / "references/accuracy.md")
    match = re.search(r"<!-- instructions:begin -->\s*(.*?)\s*<!-- instructions:end -->", source, re.S)
    if not match:
        raise ValueError("Missing canonical persistent instruction excerpt")
    return match.group(1).strip()


def split_gemini_instructions(body: str, limit: int = GEMINI_BLOCK_BUDGET) -> list[str]:
    """Pack complete paragraphs and sentences into separate Gemini entries."""
    paragraphs = body.split("\n\n")
    pieces = []
    for paragraph in paragraphs:
        if len(paragraph) <= limit:
            pieces.append(paragraph)
            continue
        sentences = re.split(r"(?<=\.) (?=[A-Z])", paragraph)
        current = ""
        for sentence in sentences:
            if len(sentence) > limit:
                raise ValueError("Gemini instruction sentence exceeds packaging budget")
            candidate = current + (" " if current else "") + sentence
            if len(candidate) > limit:
                pieces.append(current)
                current = sentence
            else:
                current = candidate
        if current:
            pieces.append(current)

    blocks = []
    current = ""
    for piece in pieces:
        candidate = current + ("\n\n" if current else "") + piece
        if len(candidate) > limit:
            blocks.append(current)
            current = piece
        else:
            current = candidate
    if current:
        blocks.append(current)
    return blocks


def render_web(root: Path = ROOT) -> dict[Path, str]:
    sources = shared_paths() + [TEMPLATES / name for name in ("web-skill.md", "chatgpt.txt", "gemini.txt")]
    stamp = "<!-- Generated by scripts/generate-web-artifacts.py. Source SHA-256: " + digest(root, sources) + " -->\n"
    skill = read(root, TEMPLATES / "web-skill.md")
    _, frontmatter, body = skill.split("---", 2)
    outputs = {WEB_SKILL / "SKILL.md": "---" + frontmatter + "---\n\n" + stamp + body.lstrip("\n")}
    for name in SHARED:
        outputs[WEB_SKILL / "references" / (name + ".md")] = read(root, CORE / "references" / (name + ".md"))
    for platform in ("chatgpt", "gemini"):
        body = read(root, TEMPLATES / (platform + ".txt")).replace("{{core}}", persistent_core(root)).strip()
        if "{{" in body:
            raise ValueError("Unresolved template token")
        if platform == "chatgpt" and len(body) > 1500:
            raise ValueError(f"ChatGPT block exceeds the 1,500-character packaging budget: {len(body)}")
        header = "# " + PROJECT_TITLE + ": " + ("ChatGPT Custom Instructions" if platform == "chatgpt" else "Instructions for Gemini") + "\n\n" + stamp + "\n"
        if platform == "gemini":
            blocks = split_gemini_instructions(body)
            instructions = "Add each numbered block as a separate Gemini instruction. Copy only the text inside each block. Check the limit shown by your account.\n\n"
            for index, block in enumerate(blocks, 1):
                instructions += f"## Instruction {index} of {len(blocks)}\n\nBlock length: {len(block)} characters.\n\n```text\n{block}\n```\n\n"
            outputs[Path("web-instructions/gemini.md")] = header + instructions.rstrip() + "\n"
        else:
            outputs[Path("web-instructions/chatgpt.md")] = (
                header + "Copy only the text inside the block.\n\n"
                + f"Block length: {len(body)} characters. Check the limit shown by your account.\n\n"
                + "```text\n" + body + "\n```\n"
            )
    return outputs


def strip_frontmatter(text: str) -> str:
    return text.split("---", 2)[2].lstrip("\n")


def render_claude(root: Path = ROOT) -> str:
    paths = [CORE / "SKILL.md"] + shared_paths() + [CORE / "references" / (name + ".md") for name in LOCAL]
    body = strip_frontmatter(read(root, CORE / "SKILL.md"))
    body = re.sub(r"^# .*\n", "", body, count=1).lstrip("\n")
    for name in (*SHARED, *LOCAL):
        reference = read(root, CORE / "references" / (name + ".md"))
        reference = re.sub(r"^# .*\n", "", reference, count=1).lstrip("\n")
        reference = re.sub(r"^(#{2,5}) ", r"\1# ", reference, flags=re.M)
        body += "\n## Embedded " + name + "\n\n" + reference
    for name in (*SHARED, *LOCAL):
        body = re.sub(r"\[([^\]]+)\]\((?:references/)?" + re.escape(name) + r"\.md\)", r"[\1](#embedded-" + name.lower() + ")", body)
    return (
        "---\nname: " + PROJECT_NAME + "\ndescription: Coding-agent writing with local checks and en-US, zh-TW, and ja-JP guidance.\nkeep-coding-instructions: true\n---\n\n"
        + "<!-- Source SHA-256: " + digest(root, paths) + " -->\n\n# " + PROJECT_TITLE + " for Claude Code\n\n" + body
    )
